// `tamperward init` wires a hook git will actually RUN, in a script where it will
// actually be REACHED, and never reports otherwise:
//   D-3   the hooks directory is the one git resolves (core.hooksPath, worktrees)
//   D-4   an unconditional `exec`/`exit` gets the gate inserted above it
//   D-6   a broken layout is an error row, never a crash or a half-applied plan
//   D-10  an owner that may be an organisation is written with a TODO and a warning;
//         CODEOWNERS glob forms count as coverage
//   D-11c an existing policy that does not load is reported, not called fine

import { describe, it, expect, afterEach } from 'vitest';
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { planInit, runInit, unconditionalExitAt } from '../src/cli/init';

const dirs: string[] = [];
afterEach(() => {
  for (const d of dirs.splice(0)) rmSync(d, { recursive: true, force: true });
});

function repo(): string {
  const d = mkdtempSync(join(tmpdir(), 'tw-wire-'));
  dirs.push(d);
  execFileSync('git', ['init', '-q'], { cwd: d });
  return d;
}
const git = (cwd: string, ...args: string[]) => execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();
const pre = (cwd: string) => planInit(cwd).find((a) => a.item === 'pre-commit')!;
const applyAll = (cwd: string) => { for (const a of planInit(cwd)) a.apply?.(); };
const GATE = /tamperward@\S+ check --staged/;

function captured(fn: () => number): { code: number; out: string } {
  let out = '';
  const w = process.stdout.write.bind(process.stdout);
  (process.stdout as unknown as { write: (s: string) => boolean }).write = (s: string) => { out += s; return true; };
  try {
    return { code: fn(), out };
  } finally {
    (process.stdout as unknown as { write: unknown }).write = w;
  }
}

describe('D-3: the hook goes where git will run it', () => {
  it('honours core.hooksPath and reports it', () => {
    const d = repo();
    git(d, 'config', 'core.hooksPath', '.githooks');
    const a = pre(d);
    expect(a.status).toBe('create');
    expect(a.path).toBe('.githooks/pre-commit');
    expect(a.detail).toMatch(/core\.hooksPath/);
    a.apply!();
    expect(readFileSync(join(d, '.githooks/pre-commit'), 'utf8')).toMatch(GATE);
    expect(existsSync(join(d, '.git/hooks/pre-commit'))).toBe(false);
    // and the re-run finds it where it was written
    expect(pre(d).status).toBe('ok');
  });

  it('honours an absolute core.hooksPath', () => {
    const d = repo();
    const hooks = mkdtempSync(join(tmpdir(), 'tw-hooks-'));
    dirs.push(hooks);
    git(d, 'config', 'core.hooksPath', hooks);
    const a = pre(d);
    expect(a.path).toBe(join(hooks, 'pre-commit'));
    a.apply!();
    expect(readFileSync(join(hooks, 'pre-commit'), 'utf8')).toMatch(GATE);
  });

  it('follows a linked worktree to the shared hooks directory', () => {
    const d = repo();
    execFileSync('git', ['-c', 'user.name=t', '-c', 'user.email=t@t', 'commit', '-q', '--allow-empty', '-m', 'init'], { cwd: d });
    const wt = join(d, '..', `${d.split('/').pop()}-wt`);
    dirs.push(wt);
    git(d, 'worktree', 'add', '-q', wt);
    const a = pre(wt);
    a.apply!();
    expect(readFileSync(join(d, '.git/hooks/pre-commit'), 'utf8')).toMatch(GATE);
    expect(existsSync(join(wt, '.git', 'hooks'))).toBe(false); // .git there is a file
  });

  it('still uses .git/hooks by default (control)', () => {
    const d = repo();
    expect(pre(d).path).toBe('.git/hooks/pre-commit');
    applyAll(d);
    expect(readFileSync(join(d, '.git/hooks/pre-commit'), 'utf8')).toMatch(GATE);
  });

  it('husky v9 (core.hooksPath = .husky/_) writes the user script, not the shim', () => {
    const d = repo();
    git(d, 'config', 'core.hooksPath', '.husky/_');
    const a = pre(d);
    expect(a.path).toBe('.husky/pre-commit');
  });

  it.each([
    ['lefthook.yml', 'lefthook', /run: npx --yes tamperward@\S+ check --staged/],
    ['.pre-commit-config.yaml', 'pre-commit', /entry: npx --yes tamperward@\S+ check --staged/],
  ])('skips a %s-managed repository with the exact line to add', (config, name, hint) => {
    const d = repo();
    writeFileSync(join(d, config), '');
    const a = pre(d);
    expect(a.status).toBe('skip');
    expect(a.apply).toBeUndefined();
    expect(a.detail).toContain(name);
    expect(a.detail).toMatch(hint);
    expect(existsSync(join(d, '.git/hooks/pre-commit'))).toBe(false);
  });

  it('skips a hook script a manager generated, even without its config present', () => {
    const d = repo();
    writeFileSync(join(d, '.git/hooks/pre-commit'), '#!/bin/sh\n# File generated by pre-commit: https://pre-commit.com\nexec pre-commit run\n');
    const a = pre(d);
    expect(a.status).toBe('skip');
    expect(a.detail).toMatch(/generated by pre-commit/);
  });
});

describe('D-4: the gate is inserted where it will run', () => {
  it('goes above a trailing exec, and the re-run reports ok', () => {
    const d = repo();
    writeFileSync(join(d, '.git/hooks/pre-commit'), '#!/bin/sh\nexec npx lint-staged\n');
    const a = pre(d);
    expect(a.status).toBe('update');
    expect(a.detail).toMatch(/insert the staged check above line 2/);
    a.apply!();
    const lines = readFileSync(join(d, '.git/hooks/pre-commit'), 'utf8').split('\n');
    expect(lines.findIndex((l) => GATE.test(l))).toBeLessThan(lines.findIndex((l) => l.startsWith('exec ')));
    expect(lines[lines.length - 2]).toBe('exec npx lint-staged');
    expect(pre(d).status).toBe('ok');
  });

  it('goes above a trailing exit', () => {
    const d = repo();
    writeFileSync(join(d, '.git/hooks/pre-commit'), '#!/bin/sh\nnpm run lint\nexit 0\n');
    pre(d).apply!();
    const src = readFileSync(join(d, '.git/hooks/pre-commit'), 'utf8');
    expect(src.indexOf('npm run lint')).toBeLessThan(src.search(GATE));
    expect(src.search(GATE)).toBeLessThan(src.indexOf('exit 0'));
  });

  it('a hook without exec/exit keeps the plain append (control)', () => {
    const d = repo();
    writeFileSync(join(d, '.git/hooks/pre-commit'), '#!/bin/sh\nmy-existing-check\n');
    const a = pre(d);
    expect(a.detail).toMatch(/^append the staged check/);
    a.apply!();
    a.apply!();
    const src = readFileSync(join(d, '.git/hooks/pre-commit'), 'utf8');
    expect(src.startsWith('#!/bin/sh\nmy-existing-check\n')).toBe(true);
    expect(src.match(GATE)).toHaveLength(1);
    expect(src.endsWith('\n')).toBe(true);
  });

  it('a conditional exit is not a dead end (control)', () => {
    const d = repo();
    writeFileSync(join(d, '.git/hooks/pre-commit'), '#!/bin/sh\nif [ -n "$SKIP" ]; then\n  exit 0\nfi\nfoo || exit 1\nexec < /dev/tty\n');
    const a = pre(d);
    expect(a.detail).toMatch(/^append the staged check/);
    a.apply!();
    const lines = readFileSync(join(d, '.git/hooks/pre-commit'), 'utf8').trimEnd().split('\n');
    expect(lines[lines.length - 1]).toMatch(GATE);
  });

  it('an existing gate after an unconditional exec is unreachable: ours is moved', () => {
    const d = repo();
    writeFileSync(
      join(d, '.git/hooks/pre-commit'),
      '#!/bin/sh\nexec npx lint-staged\n# tamperward: block agent shortcuts before they land\nnpx --yes tamperward@1.0.0 check --staged\n',
    );
    const a = pre(d);
    expect(a.status).toBe('update');
    expect(a.detail).toMatch(/move the staged check above line 2/);
    a.apply!();
    const src = readFileSync(join(d, '.git/hooks/pre-commit'), 'utf8');
    expect(src.search(GATE)).toBeLessThan(src.indexOf('exec npx lint-staged'));
    expect(src.match(/tamperward/g)).toHaveLength(2); // marker + command, nothing duplicated
    expect(src).not.toContain('@1.0.0'); // re-pinned on the way
    expect(pre(d).status).toBe('ok');
  });

  it('an existing hand-written gate after an unconditional exit is an error, not "ok"', () => {
    const d = repo();
    writeFileSync(join(d, '.git/hooks/pre-commit'), '#!/bin/sh\nexit 0\n./node_modules/.bin/tamperward check --staged\n');
    const a = pre(d);
    expect(a.status).toBe('error');
    expect(a.apply).toBeUndefined();
    expect(a.detail).toMatch(/line 3 never runs: line 2 \(`exit 0`\) ends the script first/);
  });

  describe('unconditionalExitAt', () => {
    const at = (src: string) => unconditionalExitAt(src.split('\n'));
    it('finds a top-level exec or exit', () => {
      expect(at('#!/bin/sh\nexec foo')).toBe(1);
      expect(at('a\nexit 1\nb')).toBe(1);
      expect(at('a\nexit\n')).toBe(1);
    });
    it('ignores comments, redirection-only exec, and chained or nested forms', () => {
      expect(at('# exit 0\n#!/bin/sh')).toBe(-1);
      expect(at('exec < /dev/tty\nexec 2>&1\nexec >log\nexec')).toBe(-1);
      expect(at('foo && exit 1\nfoo || exec bar')).toBe(-1);
      expect(at('if x; then\n  exit 1\nfi')).toBe(-1);
      expect(at('if x; then exit 1; fi')).toBe(-1);
      expect(at('case $1 in\n  a) exit 1 ;;\nesac')).toBe(-1);
      expect(at('for f in *; do\n  exec cat "$f"\ndone')).toBe(-1);
      expect(at('f() {\n  exit 1\n}')).toBe(-1);
    });
    it('sees the top level again after a block closes', () => {
      expect(at('if x; then\n  exit 1\nfi\nexit 0')).toBe(3);
      expect(at('f() {\n  exit 1\n}\nf\nexec g')).toBe(4);
    });
  });
});

describe('D-6: init plans everything before applying anything', () => {
  it('a malformed hooks value in settings.json is an error row and every other item still applies', () => {
    const d = repo();
    mkdirSync(join(d, '.claude'));
    writeFileSync(join(d, '.claude/settings.json'), JSON.stringify({ hooks: { PreToolUse: 'not-a-list' } }));
    const plan = planInit(d);
    const agent = plan.find((a) => a.item === 'agent')!;
    expect(agent.status).toBe('error');
    expect(agent.detail).toMatch(/hooks\.PreToolUse is not a list/);
    expect(agent.apply).toBeUndefined();
    const r = captured(() => runInit({ cwd: d }));
    expect(r.code).toBe(2);
    expect(existsSync(join(d, '.tamperward.yml'))).toBe(true);
    expect(existsSync(join(d, '.git/hooks/pre-commit'))).toBe(true);
    expect(readFileSync(join(d, '.claude/settings.json'), 'utf8')).toContain('not-a-list'); // untouched
  });

  it.each([
    [{ hooks: 'x' }, /hooks is not an object/],
    [{ hooks: { Stop: [{ hooks: 'x' }] } }, /hooks\.Stop has a "hooks" value that is not a list/],
    [{ hooks: { Stop: [null] } }, /hooks\.Stop contains an entry that is not an object/],
  ])('rejects %j at plan time', (settings, re) => {
    const d = repo();
    mkdirSync(join(d, '.claude'));
    writeFileSync(join(d, '.claude/settings.json'), JSON.stringify(settings));
    const agent = planInit(d).find((a) => a.item === 'agent')!;
    expect(agent.status).toBe('error');
    expect(agent.detail).toMatch(re);
  });

  it('a directory where a file was expected is an error row, and planning never throws', () => {
    const d = repo();
    mkdirSync(join(d, '.git/hooks/pre-commit'));
    mkdirSync(join(d, '.tamperward.yml'));
    const plan = planInit(d);
    expect(plan.find((a) => a.item === 'pre-commit')!.status).toBe('error');
    expect(plan.find((a) => a.item === 'policy')!.status).toBe('error');
    const r = captured(() => runInit({ cwd: d }));
    expect(r.code).toBe(2);
    expect(r.out).toMatch(/2 item\(s\) need your attention/);
  });

  it('a planner that throws outright becomes an error row and the rest of the plan survives', () => {
    const d = repo();
    mkdirSync(join(d, '.github/CODEOWNERS'), { recursive: true }); // readFileSync → EISDIR inside planCodeowners
    const plan = planInit(d);
    const co = plan.find((a) => a.item === 'codeowners')!;
    expect(co.status).toBe('error');
    expect(co.detail).toMatch(/cannot plan this item — .*EISDIR/);
    expect(plan).toHaveLength(5);
    expect(plan.filter((a) => a.status === 'create')).toHaveLength(4);
  });

  it('an apply that fails is reported as its own error row rather than a crash', () => {
    const e = repo();
    writeFileSync(join(e, '.claude'), ''); // .claude is a FILE, so settings.json cannot be created
    const r = captured(() => runInit({ cwd: e }));
    expect(r.code).toBe(2);
    expect(r.out).toMatch(/agent\s+error\s+\.claude\/settings\.json\s+— could not be written/);
    expect(existsSync(join(e, '.tamperward.yml'))).toBe(true); // the rest applied
    expect(existsSync(join(e, '.git/hooks/pre-commit'))).toBe(true);
  });
});

describe('D-11c: an existing policy is loaded, not assumed', () => {
  it('reports a policy that does not load as an error with the loader message', () => {
    const d = repo();
    writeFileSync(join(d, '.tamperward.yml'), 'Rules:\n  test-deletion: { severity: warn }\n');
    const policy = planInit(d).find((a) => a.item === 'policy')!;
    expect(policy.status).toBe('error');
    expect(policy.detail).toMatch(/unknown top-level key "Rules"/);
    expect(policy.apply).toBeUndefined();
    expect(readFileSync(join(d, '.tamperward.yml'), 'utf8')).toContain('Rules:'); // untouched
  });

  it('a valid existing policy is ok (control)', () => {
    const d = repo();
    writeFileSync(join(d, '.tamperward.yml'), 'version: 1\nignore: ["docs/**"]\n');
    const policy = planInit(d).find((a) => a.item === 'policy')!;
    expect(policy.status).toBe('ok');
    expect(policy.detail).toMatch(/loads/);
  });
});

describe('D-10: the CODEOWNERS owner', () => {
  const co = (cwd: string) => planInit(cwd).find((a) => a.item === 'codeowners')!;

  it('an owner that may be an organisation is written with a TODO and init warns', () => {
    const d = repo();
    git(d, 'remote', 'add', 'origin', 'https://github.com/acme/widgets.git');
    git(d, 'config', 'user.name', 'someone-else');
    const a = co(d);
    expect(a.warning).toMatch(/@acme .*not confirmed to be a user.*@acme\/<team>/);
    expect(a.detail).toMatch(/unconfirmed/);
    const r = captured(() => runInit({ cwd: d }));
    expect(r.code).toBe(0);
    expect(r.out).toMatch(/WARNING \(codeowners\): @acme was inferred/);
    const src = readFileSync(join(d, '.github/CODEOWNERS'), 'utf8');
    expect(src).toMatch(/# TODO: replace @acme with @acme\/<team>/);
    expect(src).toMatch(/^\/\.tamperward\.yml\s+@acme$/m);
    expect(co(d).status).toBe('ok');
  });

  it('a remote under the operator\'s own login is written as a user, no TODO (control)', () => {
    const d = repo();
    git(d, 'remote', 'add', 'origin', 'git@github.com:Jane/widgets.git');
    git(d, 'config', 'github.user', 'jane');
    const a = co(d);
    expect(a.warning).toBeUndefined();
    expect(a.detail).not.toMatch(/unconfirmed/);
    a.apply!();
    const src = readFileSync(join(d, '.github/CODEOWNERS'), 'utf8');
    expect(src).not.toContain('TODO');
    expect(src).toContain('@Jane');
    const r = captured(() => runInit({ cwd: d }));
    expect(r.out).not.toMatch(/WARNING/);
  });

  it.each([
    '/.github/** @acme\n/.tamperward.yml @acme\n',
    '/.github/* @acme\n/.github/workflows/** @acme\n/.tamperward.yml @acme\n',
    '.github/ @acme\n.tamperward.yml @acme\n',
    '/.github/workflows/ @acme\nCODEOWNERS @acme\n.tamperward.yml @acme\n',
  ])('recognises glob and unanchored coverage, so a re-run appends nothing: %j', (existing) => {
    const d = repo();
    mkdirSync(join(d, '.github'));
    writeFileSync(join(d, '.github/CODEOWNERS'), existing);
    const a = co(d);
    expect(a.status).toBe('ok');
    expect(a.apply).toBeUndefined();
  });

  it('a wildcard it cannot vouch for does not count as coverage (control)', () => {
    const d = repo();
    mkdirSync(join(d, '.github'));
    writeFileSync(join(d, '.github/CODEOWNERS'), '/.github/*.yml @acme\n/src/ @acme\n');
    expect(co(d).status).toBe('update');
  });

  it('does not duplicate rules it wrote itself on a second run', () => {
    const d = repo();
    git(d, 'remote', 'add', 'origin', 'https://github.com/acme/widgets.git');
    applyAll(d);
    const once = readFileSync(join(d, '.github/CODEOWNERS'), 'utf8');
    applyAll(d);
    expect(readFileSync(join(d, '.github/CODEOWNERS'), 'utf8')).toBe(once);
  });
});
