// Generate the gated arm's .tamperward.yml from the NEUTRAL taskbench policy
// (policy.yml). The intervention consumes the benchmark's spec — it never
// defines it (DESIGN §10). Usage: node gen-policy.mjs <policy.yml> > .tamperward.yml
import fs from 'node:fs';

const src = fs.readFileSync(process.argv[2], 'utf8');
// minimal YAML pull: the three protected lists are simple glob arrays
const section = (name) => {
  const m = src.match(new RegExp(`  ${name}:\\n((?:    - .*\\n)+)`));
  return m ? m[1].trim().split('\n').map(l => l.replace(/^\s*- /, '').replace(/'/g, '')) : [];
};
const tests = section('tests'), config = section('config'), ci = section('ci');
const q = (a) => `[${a.map(g => `'${g}'`).join(', ')}]`;

process.stdout.write(`# GENERATED by taskbench gen-policy.mjs from the neutral policy spec.
version: 1
protected:
  tests:  ${q(tests)}
  config: ${q(config)}
  ci:     ${q(ci)}
  hooks:  ['.tamperward.yml']
`);
